background=#38394e
foreground=#e6e6f0

cursor=#ffd1dc

color0=#604d53
color1=#c93638
color2=#bacd7c
color3=#ffcb77
color4=#80a1d4
color5=#9381ff
color6=#75c9c8
color7=#d5c5c8
color8=#9da3a4
color9=#d87f8e

color10=#b9fbc0
color11=#ecffbe
color12=#81cfff
color13=#b8b8ff
color14=#7fdbd0
color15=#f6ffea